feat(app): use tolerations and affinities from CRC
SwissDataScienceCenter/renku-notebooks pull request #1626
Opened 2023-09-11 13:16 UTC by olevski

closes https://github.com/SwissDataScienceCenter/renku-notebooks/issues/1582
closes https://github.com/SwissDataScienceCenter/renku-notebooks/issues/1583

/deploy #persist

This does not break the existing API. Even if the CRC does not have tolerations/affinities in the response the notebooks service will be happy.

2023-09-27 08:05 UTC, Panaetius requested changes

2023-09-27 08:05 UTC, Panaetius commented on renku_notebooks/api/amalthea_patches/general.py
> +        ]
```suggestion
        tolerations = [
            {
                "key": key,
                "operator": "Equal",
                "value": "user",
                "effect": "NoSchedule",
            },
        ] + config.sessions.tolerations
```

2023-09-27 08:15 UTC, mohammad-alisafaee submitted a review, later dismissed
LGTM, thanks!

2023-09-28 12:01 UTC, Panaetius approved these changes

2023-09-28 13:48 UTC, merged