feat: cleanup PVS and autosave branches
SwissDataScienceCenter/renku-notebooks pull request #611
Opened 2021-04-19 23:12 UTC by olevski

closes #576 

Note on terminology: I use PVS and pvc interchangeably below.

The logic is the same as discussed in #576, namely old autosave branches or pvcs are removed when:
- the commit where the new session is launched has any child commit that has an autosave branch or pvc tied to it
- in the case of the pvc we check if this autosave pvc is part of a running pod and if not the pvc is deleted
- branches are similarly deleted - without the need for checking for running pods

In addition to the above the following changes were made:
- Autosave branches are created and used alongside with pvcs because this way we can let the user recover if they commit changes, but do not push them and then they go and shut down their session. In this case only the autosave branches can capture the changes because pvcs are deleted when user sessions are gracefully (i.e. purposefully) deleted. Also it is hard to check from the server side if a user session has a clean commit history or not when a pod is being deleted.
- Since even when pvcs are enabled autosave branches are still used (see bullet point above), the autosave deletion logic will now remove autosave branches if it finds a matching pvc.
- pre-stop script that creates the autosave branch was edited to use `git stash`. This is because in the current code this script does not revert to the original (dirty) state of the repo after it creates the autosave branch. This made perfect sense when there were no pvcs but now it does not. Now it does not make sense because the pvc is preferentially used to restore from an autosave rather than an autosave branch. And the creation of the autosave branch which is done in the pvc itself should not change the state of the pvc to something that is different than where the user left off.

Deployed at https://tasko.dev.renku.ch/ with support for pvcs.

2021-04-20 13:22 UTC, lorenzo-cavazzi commented
If we are going to use autosave branches all the time when the user gracefully stops from the UI (which is great in my opinion) and we delete the previous content when starting a new environment, then I think we should revisit how we save them.

![Screenshot_20210420_145025](https://user-images.githubusercontent.com/43481553/115400735-ec5e7f80-a1e9-11eb-8d37-759481c6bf23.png)

Something confusing for the user is how we associate the autosave with the starting commit. Let's say the user starts from commit `abcdef1` and creates more content (let's say commit `abcdef2`) and pushes. He keeps working on that and he accidentally stops the environment, creating an autosave with the non-pushed content `abcdef3`. Currently, the autosaved branch refers to `abcdef1` even if the user probably expects that to be attached to `abcdef2`.

The following is an example where I started the environment from `b1ab2e7d`, pushed 2 commits, and kept working locally adding other content. On the right, the autosave is bound to `b1ab2e7d`. The star identifying the autosave would be even harder to noticed if I pushed more commits in between (say 10 or 20).

![Screenshot_20210420_150504](https://user-images.githubusercontent.com/43481553/115401173-6858c780-a1ea-11eb-930f-b842ef3f35f3.png)

Even though that problem is independent of this PR, I think we should address it before merging. Otherwise, a user who doesn't notice the autosave associated with an old commit, would lose everything as soon as he starts a new environment from the latest commit.

Would it make sense to bind the commit to the latest pushed combination of branch/commit (with a preference for the current branch name in case of conflict) instead of using the starting branch/commit?

2021-04-20 15:39 UTC, olevski commented
@lorenzo-cavazzi this is a very good find and it is easily fixable for the autosave branches. However once we change this for the autosave branches there is a difference between the naming of the autosave pvcs and branches. The autosave pvcs are always annotated with the initial commit that spawned the user session but the autosave branches naming follows whatever commits the user pushed as you suggested. It would be nice if we could do the same for the pvcs, however this is not straightforward and it would require continually patching the user pvc to keep track with all the commits that are pushed to the remote by the user. This is a problem because it is hard to get information about the local state of a user session on the server side where one would have to patch the pvc.

Because of this I think we should stick to what we currently have and explain this well in the docs and communicate it clearly in the UI. I am open to alternatives however - if you have any ideas on how to resolve this issue with the pvcs.

2021-04-20 15:48 UTC, olevski commented
One thing that comes to mind is to have a separate dropdown/menu that shows all the commits that result in autosaves in the UI rather than have them both combined and distinguish with a `*`. If we have a separate list with autosaves we can remove the corresponding entry in the regular list so that we avoid duplicating things and we prevent the user from launching a 'fresh' session as long as an autosave exists. 

Another thing we can do is prevent the user from launching sessions from commits which are children of the autosave as long as the autosave branch or pvc is around. This way we force the user to resolve their unsaved work before continuing to launch new sessions.

2021-04-21 06:21 UTC, lorenzo-cavazzi commented
I agree that having different behaviors between autosave branches and pvs may be confusing. If updating the branch/commit label attached to the pvs is not feasible at release time, then it's probably better to stay with the current solution for autosave branches, even though that will keep being confusing for users.

I'm not sure having a separate list and forcing the user to pick a commit from there leads to a better UX. On the other hand, I like the idea of showing a warning when starting from a more recent commit than the one with autosaved content. We still can't show much more details for pvs since the content is not accessible until the environment is up, but it's probably the best we can do.

2021-04-23 12:21 UTC, olevski commented
So I wanted to summarize all the scenarios that this should cover and that I tested. Also I wanted to explain how the removal of old autosave pvcs or branches is done.

![image](https://user-images.githubusercontent.com/16360283/115869872-ca116f80-a43e-11eb-8a36-50b11d26d929.png)

![image](https://user-images.githubusercontent.com/16360283/115869908-d5fd3180-a43e-11eb-8542-778a5394e69c.png)

I added extra logic to the code that deletes autosaves from parent commits so that it checks how "far" these commits are from the commit where the new session is launched. If the commits are farther (i.e. older) than 5 commits then the autosave pvc and/or branch is deleted. Deleting an autosave branch or pvc tied to an immediate parent seemed a bit extreme.

Let me know if you agree with these changes.

2021-04-28 13:44 UTC, lorenzo-cavazzi commented
I'm not sure the number of commits should play any role. Some people commit very often, others prefer to commit rarely -- though renku creates commits for you when using renku commands.
I would keep the logic simple and apply the same behavior, independent of how many commits there are in between the launched session and the reference for the saved session.

2021-04-30 12:49 UTC, olevski commented
Ok I will remove the logic that looks at this 'commit distance' for removing autosave branches and PVs.

2021-05-03 15:03 UTC, olevski commented
Ok I removed the commit distance requirement and tested in my dev delployment. Everything works.

2021-05-03 17:00 UTC, ableuler requested changes
Looks very good, works as advertised and carefully handles all possible scenarios I can think of. Just two suggestions for small improvements.

2021-05-04 07:31 UTC, olevski commented on renku_notebooks/api/classes/server.py
> +        def _has_parent(commit, parent, gl_project):
Cool I did not know if this api endpoint. I will add the change.

2021-05-04 07:32 UTC, olevski commented on renku_notebooks/api/classes/server.py
> +                storage_class=current_app.config["NOTEBOOKS_SESSION_PVS_STORAGE_CLASS"],
This is easy I will make the change

2021-05-04 11:57 UTC, ableuler approved these changes

2021-05-04 12:22 UTC, merged