feat(app): version endpoint
SwissDataScienceCenter/renku-notebooks pull request #938
Opened 2022-02-17 21:55 UTC by mohammad-sdsc

Fixes #879

2022-02-21 18:10 UTC, olevski requested changes
Thanks Mohammad just a minor change in how we pull in the version. What you suggested is fine, but it is a bit less convoluted to pull this through Helm rather than parse the template when the image is built. Also we already pull in a lot of configuration settings from the values file like this.

2022-02-21 18:10 UTC, olevski commented on renku_notebooks/api/__init__.py
> +                    "anonymous_sessions_enabled": config.ANONYMOUS_SESSIONS_ENABLED,
```suggestion
                    "anonymousSessionsEnabled": config.ANONYMOUS_SESSIONS_ENABLED,
```

2022-02-21 18:10 UTC, olevski commented on renku_notebooks/api/__init__.py
> +                    "anonymous_sessions_enabled": config.ANONYMOUS_SESSIONS_ENABLED,
This is more in line with naming in the values file. And I would like to transition to returning camelCase in endpoints as much as possible. Whereas internal python code would be snake_case.

2022-02-21 18:10 UTC, olevski commented on renku_notebooks/api/__init__.py
> +                    "s3_mount_enabled": config.S3_MOUNTS_ENABLED,
```suggestion
                    "cloudstorageS3Enabled": config.S3_MOUNTS_ENABLED,
```

2022-02-21 18:10 UTC, olevski commented on renku_notebooks/api/__init__.py
> +                    "s3_mount_enabled": config.S3_MOUNTS_ENABLED,
...same as above - this is a bit more consistent with existing terminology.

2022-02-21 18:10 UTC, olevski commented on tests/integration/test_session_creation.py
> +def test_version_endpoint():
Thanks for adding this 🥇

2022-02-23 09:24 UTC, olevski commented
One more thing I just thought of Mohammad. Please remember the register the schema so that it properly works with swagger here: https://github.com/SwissDataScienceCenter/renku-notebooks/blob/master/renku_notebooks/__init__.py#L142.

2022-02-23 16:18 UTC, mohammad-sdsc commented on Dockerfile
> +RUN echo "__version__ = \"$(yaml-get --query .version Chart.yaml)\"" > renku_notebooks/version.py
Thanks! This is much cleaner.

2022-02-28 13:10 UTC, olevski requested changes

2022-02-28 13:10 UTC, olevski commented on renku_notebooks/api/notebooks.py
> +                    "cloudstorageEnabled": config.S3_MOUNTS_ENABLED,
@mohammad-sdsc this is supposed to have one more level of keys that indicate the type of storage.

```suggestion
                    "cloudstorageEnabled": {
                        "s3": config.S3_MOUNTS_ENABLED,
                    },
```

2022-02-28 16:08 UTC, olevski approved these changes

2022-02-28 16:08 UTC, merged